name: build-legacy

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PUBSPEC: "pubspec.yaml"
  TARGET: "macos"
  RELEASE: "build/macos/Build/Products/Release/click.app"

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-legacy.yml"

jobs:
  pre:
    runs-on: ubuntu-24.04
    outputs:
      pubspec: ${{ env.PUBSPEC }}
      target: ${{ env.TARGET }}
      release: ${{ env.RELEASE }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"

  ready:
    needs:
      - pre
    uses: LaoWangFantasy/Flutter-Actions/.github/workflows/get-version.yml@master
    with:
      pub_path: ${{ needs.pre.outputs.pubspec }}

  build-macos-legacy:
    runs-on: macos-13
    needs:
      - pre
      - ready
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      -
        run: flutter --version
      -
        run: flutter pub get
      -
        run: flutter test
      -
        run: flutter build ${{ needs.pre.outputs.target }}
      - 
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
          PREFIX="${{ needs.pre.outputs.release }}"
          EXTENSION="${PREFIX##*.}"
          BIN="$REPO_NAME-${{ needs.pre.outputs.target }}-legacy-$VERSION"

          mv "${{ needs.pre.outputs.release }}" $BIN.$EXTENSION
          hdiutil create -volname "$BIN" -srcfolder "$BIN.$EXTENSION" -ov -format UDZO "$BIN.dmg"
          gh release upload $VERSION $BIN.dmg
        env:
          VERSION: ${{ needs.ready.outputs.version }}
        shell: bash
        name: Upload