name: build-legacy

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PUBSPEC: "pubspec.yaml"

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-legacy.yml"

jobs:
  pre:
    runs-on: ubuntu-24.04
    outputs:
      pubspec: ${{ env.PUBSPEC }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"

  ready:
    needs:
      - pre
    uses: LaoWangFantasy/Flutter-Actions/.github/workflows/get-version.yml@master
    with:
      pub_path: ${{ needs.pre.outputs.pubspec }}

  build:
    runs-on: macos-12
    needs:
      - pre
      - ready
    strategy:
      matrix:
        target: [macos, ios]
        include:
          - target: macos
            build: "build macos --release"
            release: "build/macos/Build/Products/Release/atom.app"
          - target: ios
            build: "build ios --release --no-codesign"
            release: "build/ios/Release-iphoneos/Runner.app"

    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      -
        run: flutter --version
      -
        run: flutter pub get
      -
        run: flutter test
      - 
        name: Build for ${{ matrix.target }}
        run:
          flutter ${{ matrix.build }}
        shell: bash
      - 
        run: |
          REPO_NAME="${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/}"
          PREFIX="${{ matrix.release }}"
          EXTENSION="${PREFIX##*.}"
          BIN="$REPO_NAME-${{ matrix.target }}"

          mv "${{ matrix.release }}" $BIN.$EXTENSION
          mkdir -p dist
          hdiutil create -volname "$BIN" -srcfolder "$BIN.$EXTENSION" -ov -format UDZO "./dist/$BIN-legacy.dmg"
          gh release upload ${{ needs.ready.outputs.version }} ./dist/$BIN-legacy.dmg
        shell: bash
        name: Upload