name: build-windows

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  WINDOWS_PFX_PASSWD: ${{ secrets.WINDOWS_PFX_PASSWD }}
  PUBSPEC: "pubspec.yaml"
  TARGET: "windows"
  RELEASE: "build/windows/x64/runner/Release"

permissions:
  contents: write

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ci"]
    types:
      - completed
  push:
    branches:
      - "master"
    paths:
      - ".github/workflows/build-windows.yml"

jobs:
  pre:
    runs-on: ubuntu-24.04
    outputs:
      pubspec: ${{ env.PUBSPEC }}
      target: ${{ env.TARGET }}
      release: ${{ env.RELEASE }}
      pfx: ${{ env.WINDOWS_PFX_PASSWD }}
    steps:
      - run: echo "Bypass GitHub Action Restriction"

  pkcs12:
    needs:
      - pre
    uses: LaoWangFantasy/Flutter-Actions/.github/workflows/create-pfx.yml@master
    with:
      pkcs12-secret: ${{ needs.pre.outputs.pfx }}

  ready:
    needs:
      - pre
    uses: LaoWangFantasy/Flutter-Actions/.github/workflows/get-version.yml@master
    with:
      pub_path: ${{ needs.pre.outputs.pubspec }}

  build-windows:
    runs-on: windows-2019
    needs:
      - pre
      - ready
      - pkcs12
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Flutter
        uses: subosito/flutter-action@v2.18.0
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      -
        run: choco install yq
      -
        run: flutter --version
      -
        run: flutter pub get
      -
        run: flutter test
      -
        run: flutter build windows
      -
        run: flutter pub add --dev msix
      -
        run: |
        Set-Content -Path "add.yaml" -Value @"
        msix_config:   
          display_name: $Env:GITHUB_REPOSITORY 
          publisher_display_name: $Env:GITHUB_REPOSITORY
          identity_name: company.suite.$Env:GITHUB_REPOSITORY
          app_installer:
            publish_folder_path: ${{ needs.pre.outputs.release }}
            hours_between_update_checks: 0
            automatic_background_task: true
            update_blocks_activation: true
            show_prompt: true
            force_update_from_any_version: false
          msix_version: ${{ needs.ready.outputs.version }}
          logo_path: web/icons/Icon-512.png
          capabilities: 
            - internetClient
        "@
        Get-Content pubspec.yaml, add.yaml | Set-Content pubspec.yaml
      -
        run: dart run msix:create
      -
        run: dart run msix:publish
      -
        uses: GabrielAcostaEngler/signtool-code-sign@main
        with:
          recursive: true
          cert-description: 'LaoWangFantasy'
          timestamp-server: 'http://timestamp.digicert.com'
          certificate: '${{ secrets.WINDOWS_PFX_BASE64}}'
          cert-sha1: '${{ secrets.WINDOWS_PFX_SHA }}'
          cert-password: '${{ secrets.WINDOWS_PFX_PASSWD }}'
          folder: '${{ needs.pre.outputs.release }}'
      -
        run: |
          $repoName = $Env:GITHUB_REPOSITORY -replace '^.+/', ''
          $prefix = "${{ needs.pre.outputs.release }}"
          $bin = "$repoName-${{ needs.ready.outputs.version }}-${{ needs.pre.outputs.target }}.zip"

          cd (Split-Path -Path $prefix -Parent)
          Move-Item -Path "Release" -Destination "$repoName"
          Compress-Archive -Path "$repoName" -DestinationPath $bin -CompressionLevel Optimal
          gh release upload ${{ needs.ready.outputs.version }} $bin --clobber
        shell: pwsh
        name: Upload(windows)